### ISSUE TITLE
Feature Request: Settings Snapshotting

### ISSUE THREAD

**Issue by vanto** [CharlesBlonde/libsoundtouch#16]
The sonos library allows for [snapshotting and restoring](https://github.com/SoCo/SoCo/blob/master/soco/snapshot.py) the current settings. This is nice when the box is used for TTS announcements using Home Assistant while the box is playing something else. The ideal behavior would be that the current playback stops, the announcement is played and then the playback is restored and seamlessly continues. 

It would be great if libsoundtouch could offer a similar functionality.

**Comment by CharlesBlonde** [comment]
It will become useless with the new notification API (even if I don't like the API Key requirement) but I just added a quick implementation in release 0.8.0.
