### ISSUE TITLE
Multi room state attributes in homeassistant's Soundtouch component

### ISSUE THREAD

**Issue by schneekluth** [CharlesBlonde/libsoundtouch#20]
I'm a huge fan of the Soundtouch component for homeassistant but one thing is currently missing: It would be nice to have an additional attribute on each Soundtouch device that shows whether multi room audio is currently active and that lists the current master and the belonging slaves.

That way one could create a dynamic state card to control zones e.g.:

![request_libsoundtouch](https://user-images.githubusercontent.com/5740913/33519425-72362cfa-d7a6-11e7-8628-1165914815c0.png)

**Comment by CharlesBlonde** [comment]
It would be a great feature...and I will be the first one to use it :)
I was quite busy but I will try to find a way to do it.
