### ISSUE TITLE
Accents not being showed correctly

### ISSUE THREAD

**Issue by trunet** [CharlesBlonde/libsoundtouch#4]
Hello,

Listening from some Brazilian songs here, and the names didn't encode correctly.

Example:
Playlist: Trunet Mixed
Track: MÃºsica Urbana
Artist: Capital Inicial

Track should be Música Urbana

On the refresh_status function, I got requests response.encoding being set to ISO-8859-1. If you manually set response.encoding = 'UTF-8' before parsing on minidom, it works.

The response.text.encode('utf-8') doesn't make any difference on this case.

**Comment by CharlesBlonde** [comment]
Hi @trunet and thank you for this bug report.

I'll take a look at this error quickly. Can you tell me which Python version are you using ? 2.7 ? 3.X ?

**Comment by trunet** [comment]
Hello...

I'm using python 3.5.
